final mappedErrors = {
  'string': 'The field {name} must be a string.',
  'number': 'The field {name} must be a number.',
  'unique': 'The field {name} must be unique.',
  'email': 'The field {name} must be a valid email address.',
  'phone': 'The field {name} must be a valid phone number.',
  'ipAddress': 'The field {name} must be a valid {version} address.',
  'regex': 'The field {name} must match the pattern {pattern}.',
  'url': 'The field {name} must be a valid URL.',
  'alpha': 'The field {name} must contain only alphabetic characters.',
  'minLength': 'The field {name} must be at least {min} characters long.',
  'maxLength': 'The field {name} must be at most {max} characters long.',
  'range': 'The field {name} must be between {values}.',
  'missingProperty': 'The field {name} is required.',
  'confirmed': 'The field {name} and {attemptedName}.',
  'uuid': 'The field {name} must be a valid UUID.',
  'creditCard': 'The field {name} must be a valid credit card number.',
};
